add_library(transmission_operations STATIC transmission_operations.cc)
target_include_directories(transmission_operations PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(transmission_operations PUBLIC network)

add_library(traversal STATIC traversal.cc)
target_include_directories(traversal PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(traversal PUBLIC network transmission_operations)

add_library(critical_path STATIC critical_path.cc)
target_include_directories(critical_path PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(critical_path PUBLIC network transmission_operations traversal)

add_library(tsn_configuration STATIC tsn_configuration.cc)
target_include_directories(tsn_configuration PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(tsn_configuration PUBLIC network transmission_operations traversal critical_path)

add_library(transmission_graph STATIC transmission_graph.cc)
target_include_directories(transmission_graph PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(transmission_graph PUBLIC network transmission_operations traversal critical_path tsn_configuration)

add_library(transmission_graph_merger STATIC transmission_graph_merger.cc)
target_include_directories(transmission_graph_merger PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(transmission_graph_merger PUBLIC network transmission_operations critical_path transmission_graph)

add_library(dgm INTERFACE)
target_link_libraries(dgm INTERFACE transmission_graph transmission_graph_merger traversal critical_path tsn_configuration)
